module.exports = {
  APP_KEY: "YAHOO!AUTH_KEY",
  APP_SECRET: "YAHOO!AUTH_SECRET",
  APP_URL: "YAHOO!APP_CALLBACK_URL",
  SESSION_SECRET: "Keyboard Cat",
  MONGO_DB: "mongodb://MONGO_ADDRESS/DATABASE",
  REDIS_HOST: "REDIS_HOST",
  REDIS_PORT: 6379
};
